# Generated by Django 6.0.1 on 2026-02-02 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='api.imovel'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='locador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locador', to='api.usuario'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='locatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locatario', to='api.usuario'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('ALUGADO', 'Alugado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='valor_aluguel',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='api.contrato'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('LOCADOR', 'Locador'), ('LOCATARIO', 'Locatário')]),
        ),
    ]
